### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by TommyJerryMairo** [persmule/amule-dlp#10]
Cannot use UPnP with amuled and amulegui:

![Screenshoot of amuled and amulegui](http://img.vim-cn.com/7c/df3c633e920f4af6ecff63f5f45f66955bd75a.png)

But, when it comes to amule, the UPnP seems available:

![Screenshoot of amule](http://img.vim-cn.com/93/a612822fcd0c96fb76be17f0399813df43c0c4.png)

What a amazing problem!

**Comment by TommyJerryMairo** [comment]
The FEATURE I have enabled are:

```
./configure \
      --prefix=/usr \
      --mandir=/usr/share/man \
      --disable-debug \
      --enable-amule-daemon \
      --enable-amulecmd \
      --enable-amule-gui \
      --enable-webserver \
      --enable-cas \
      --enable-wxcas \
      --enable-alc \
      --enable-alcc \
      --enable-geoip \
      --enable-upnp \
      --with-denoise-level=3 \
      --enable-nls \
      --enable-optimize \
      --enable-mmap \
      --enable-ccache \
      --with-wxversion=2.8
```

**Comment by biergaizi** [comment]
I'm pretty sure that `amulegui` always has similar small problems like this.

**Comment by biergaizi** [comment]
@TommyJerryMairo You may use a separate program to UPNP your ports.
