### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by yahvk-cuna** [persmule/amule-dlp#11]
../../src/Scanner.cpp: In function ‘int yy_get_next_buffer()’:
../../src/Scanner.cpp:1250:5: error: invalid initialization of non-const reference of type ‘size_t& {aka long unsigned int&}’ from an rvalue of type ‘size_t {aka long unsigned int}’
    (yy_n_chars), num_to_read );
    ~^~~~~~~~~~~
../../src/Scanner.l:28:13: note:   initializing argument 2 of ‘void ReadLexBuff(char_, size_t&, size_t)’
 static void ReadLexBuff(char_ pcBuff, size_t& riResult, size_t uMaxSize);
             ^~~~~~~~~~~
../../src/Scanner.cpp: In function ‘yy_buffer_state\* yy_scan_bytes(const char_, int)’:
../../src/Scanner.cpp:1795:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for ( i = 0; i < _yybytes_len; ++i )
               ~~^~~~~~~~~~~~~~
../../src/Scanner.l: At global scope:
../../src/Scanner.l:184:13: warning: ‘void ReadLexBuff(char_, int&, size_t)’ defined but not used [-Wunused-function]
 {
             ^  
../../src/Scanner.cpp:1816:24: warning: ‘void yy_fatal_error(const char_)’ defined but not used [-Wunused-function]
 static void yynoreturn yy_fatal_error (yyconst char_ msg )

**Comment by persmule** [comment]
Fixed by cherry-picking commit a30ca3471b80fb811d28f9645f3eda7d049b6796 from https://github.com/amule-project/amule
