### ISSUE TITLE
How can I use the DLP plugin in my amule which has already been installed ?

### ISSUE THREAD

**Issue by peinhu** [persmule/amule-dlp#19]
According to the Wiki information, it's required to install the amule while compiling the DLP plugin, therefore  I consider this program as an amule with a buit-in DLP plugin. However I already have an amule program installed in my NAS(Debian mod), so my question is whether it is possible to compile and install the DLP plugin separately, or could I embed DLP plugin into the amule program I have installed after installing amule-dlp as the Wiki says?  

从Wiki说明上来看安装这个DLP插件必需同时安装amule，也就是说这是一个整合DLP插件版的amule，而我的NAS（Debian修改版）上已经安装了amule，那么是否有可能单独编译安装DLP插件，或编译安装后嵌入到已有的amule中去呢（比如用安装说明中的方法编译安装好这个DLP版amule，然后把其中某几个文件复制到原先已有的amule中，从而使原有amule支持DLP）？

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


At least you have to replace those executables of amule with mine on
your NAS, which is not so different from replacing the whole amule,
since unmodified original amule has no interface for DLP, as well as
those UI elements related to the interface.

在 2016年09月27日 11:26, Payne 写道:


  According to the Wiki information, it's required to install the amule while compiling the DLP plugin, therefore  I consider this program as an amule with a buit-in DLP plugin. However I already have an amule program installed in my NAS(Debian mod), so my question is whether it is possible to compile and install the DLP plugin separately, or could I embed DLP plugin into the amule program I have installed after installing amule-dlp as the Wiki says?  
```

从Wiki说明上来看安装这个DLP插件必需同时安装amule，也就是说这是一个整合DLP插件版的amule，而我的NAS（Debian修改版）上已经安装了amule，那么是否有可能单独编译安装DLP插件，或编译安装后嵌入到已有的amule中去呢（比如用安装说明中的方法编译安装好这个DLP版amule，然后把其中某几个文件复制到原先已有的amule中，从而使原有amule支持DLP）？
