### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by YujiShen** [persmule/amule-dlp#22]
Error when I `make`:
```
...
/usr/include/wx-2.8/wx/datetime.h:1506:1: note: in expansion of macro ‘WX_DEFINE_USER_EXPORTED_ARRAY_PTR’
 WX_DEFINE_USER_EXPORTED_ARRAY_PTR(wxDateTimeHolidayAuthority *,
 ^
../../../../src/libs/common/Path.cpp: In constructor ‘CPath::CPath(const wxString&)’:
../../../../src/libs/common/Path.cpp:232:22: error: ‘class wxCharBuffer’ has no member named ‘length’
  if (fn.data() && fn.length()) {
                      ^
make[4]: *** [Path.o] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

System Info:
- CentOS Linux release 7.3.1611 (Core)
- Linux 3.10.0-514.2.2.el7.x86_64
- gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

Configuration:
- `--enable-optimize --with-denoise-level=3 --enable-upnp --enable-geoip --enable-nls --enable-amule-daemon --enable-amulecmd --enable-webserver --enable-alcc --enable-cas --enable-mmap --disable-amule-gui --disable-wxcas --with-boost`

- ```
   Libraries aMule will use to build:
                             wxWidgets             2.8.12 (gtk2,shared)
                             boost                 1.53
                             crypto++              5.6.2 (in /usr)
                             libupnp               1.6.19
                             libintl               system
                             libGeoIP              system
                             libpng                1.5.13
                             libgd                 2.0.34
                             zlib                  1.2.7
  ```

I found same problem raised on [aMule forum](http://forum.amule.org/index.php?topic=21514.msg110015#msg110015). It seems be fixed in revision 10981. I am not sure whether it is caused by same reason and do not know what to do.

**Comment by persmule** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    A lot of upstream improvements have
      been cherry-picked to my repository, which could have fixed the
      problem affecting you.
      
      在 2016年12月18日 06:18, Yuji Shen 写道:
    
    
      Error when I `make`:
```
...
/usr/include/wx-2.8/wx/datetime.h:1506:1: note: in expansion of macro ‘WX_DEFINE_USER_EXPORTED_ARRAY_PTR’
 WX_DEFINE_USER_EXPORTED_ARRAY_PTR(wxDateTimeHolidayAuthority *,
 ^
../../../../src/libs/common/Path.cpp: In constructor ‘CPath::CPath(const wxString&)’:
../../../../src/libs/common/Path.cpp:232:22: error: ‘class wxCharBuffer’ has no member named ‘length’
  if (fn.data() && fn.length()) {
                      ^
make[4]: *** [Path.o] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

System Info:
- CentOS Linux release 7.3.1611 (Core)
- Linux 3.10.0-514.2.2.el7.x86_64
- gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

Configuration:
- `--enable-optimize --with-denoise-level=3 --enable-upnp --enable-geoip --enable-nls --enable-amule-daemon --enable-amulecmd --enable-webserver --enable-alcc --enable-cas --enable-mmap --disable-amule-gui --disable-wxcas --with-boost`

- ```
   Libraries aMule will use to build:
                             wxWidgets             2.8.12 (gtk2,shared)
                             boost                 1.53
                             crypto++              5.6.2 (in /usr)
                             libupnp               1.6.19
                             libintl               system
                             libGeoIP              system
                             libpng                1.5.13
                             libgd                 2.0.34
                             zlib                  1.2.7
  ```

I found same problem raised on [aMule forum](http://forum.amule.org/index.php?topic=21514.msg110015#msg110015). It seems be fixed in revision 10981. I am not sure whether it is caused by same reason and do not know what to do.

**Comment by YujiShen** [comment]
Thanks for reply and update! It is solved.
