### ISSUE TITLE
是不是有内存泄露的bug?

### ISSUE THREAD

**Issue by cnfanhua** [persmule/amule-dlp#23]
运行环境： linux mint 18 kde

硬件信息： 8G ddr3L+128G SSD+i5u+NVIDIA 750M

平时开机内存占用大约在500M-1G左右，但是打开amule之后，内存缓慢飙升到7.1G(8G)。

不知道是什么情况。

**Comment by persmule** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    你用工具查看过amule具体占用了多少内存吗？
      
      在 2017年03月06日 16:47, NONE 写道:
    
    
      运行环境： linux mint 18 kde
      平时开机内存占用大约在500M-1G左右，但是打开amule之后，内存缓慢飙升到7.1G(8G)。
      不知道是什么情况。
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it
          on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/persmule/amule-dlp","title":"persmule/amule-dlp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/persmule/amule-dlp"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"是不是有内存泄露的bug? (#23)"}],"action":{"name":"View Issue","url":"https://github.com/persmule/amule-dlp/issues/23"}}}

**Comment by persmule** [comment]
IO频繁的机器上绝大部分内存被buffer和cache填满是很正常的。

**Comment by cnfanhua** [comment]
@persmule 暂时还没有，一会下班回去看看。之前打开的Teamviewer已经被关闭了。

**Comment by persmule** [comment]
居然敢用Teamviewer……

**Comment by cnfanhua** [comment]
.....
弱弱的问下，teamviewer怎么了

**Comment by persmule** [comment]
teamviewer不是自由软件，所以有危险——就不怕teamviewer的打洞服务器偷偷操纵你的机器？

**Comment by persmule** [comment]
远程控制软件我只用OpenSSH。

**Comment by persmule** [comment]
另外能不能把“内存缓慢飙升到7.1G”后 free(1) 命令的输出贴出来？

**Comment by cnfanhua** [comment]
谢谢，学习了。
一会回去贴出来

**Comment by cnfanhua** [comment]
see.
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 90.6 35.2 3376304 2759604 ?     Rl   18:34   0:38 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 92.7 40.7 3808208 3191508 ?     Rl   18:34   0:43 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 92.6 43.4 4021388 3404820 ?     Rl   18:34   0:46 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 92.5 44.3 4091348 3474780 ?     Rl   18:34   0:47 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 92.2 45.1 4151804 3535236 ?     Rl   18:34   0:47 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 93.8 45.9 4215296 3598596 ?     Rl   18:34   0:48 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 93.7 46.8 4284596 3668028 ?     Rl   18:34   0:49 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 93.4 47.6 4344920 3728484 ?     Rl   18:34   0:50 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 95.3 70.8 6165596 5549028 ?     Rl   18:34   1:16 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 96.1 84.4 7271492 6613496 ?     Rl   18:34   1:30 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 96.8 89.5 7686632 7010360 ?     Rl   18:34   1:35 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 96.8 89.7 7910108 7026632 ?     Rl   18:34   1:38 /usr/local/bin/amule
cnfanhua fanhua # ps -aux | sort -k4nr | head -n 1
fanhua   25761 96.1 89.6 8070356 7019296 ?     Rl   18:34   1:40 /usr/local/bin/amule
cnfanhua fanhua #

**Comment by persmule** [comment]
你的这个是用哪个版本的源码编译的？还有你为什么要作死地用root来跑amule？

**Comment by cnfanhua** [comment]
克隆的master版本的啊。
我没用命令打开amule。

**Comment by cnfanhua** [comment]
只是编译的时候用的root

**Comment by persmule** [comment]
你现在是作死地用root来跑桌面？

**Comment by cnfanhua** [comment]
这和amule占用高内存有何关系？？

**Comment by persmule** [comment]
一般没什么关系，不过那依旧是作死。

**Comment by persmule** [comment]
你试试看原版的amule有没有这个问题：https://github.com/amule-project/amule/

**Comment by cnfanhua** [comment]
“作死”这词，看着好不爽。
好吧。我删掉用原版的试试看。

**Comment by persmule** [comment]
用root跑桌面一旦被入侵，你硬盘上的一切都可以被一波带走，连恢复的机会都没有。

**Comment by cnfanhua** [comment]
多谢、学习了。

**Comment by l12436** [comment]
amule-dlp using 1G
I believe It has memory leak in it.
and I have using original amule, not issue so far
![image](https://user-images.githubusercontent.com/2596649/37561848-74686240-2a94-11e8-8594-dcacc293d19b.png)

**Comment by persmule** [comment]
@l12436 I am not the original author of amule-dlp. If you believe It has memory leak, could you help me to find where it is? (e.g. in commit 17a2cd29b2a8cc85c8d0ec5cdb921478faa1e72e, in which most amule-dlp-specific features are introduced)

**Comment by l12436** [comment]
I found a weird in Timer.cpp:66
the thread constant send lots of event when the memory leak happened.
I am still testing. I just slow it down when the timeout is zero.

**Comment by l12436** [comment]
it seems I still have such issue even DLP is disable. It maybe a bug in upstream master.

**Comment by l12436** [comment]
I use Ubuntu compiler argument success to prevent amule to eating lots of ram.
It seems it is the issue that amule with wxwidget 3.0,
