### ISSUE TITLE
cpu 占用100%

### ISSUE THREAD

**Issue by xf1** [persmule/amule-dlp#25]
Arch Linux直接用AUR安装的amule-dlp-git跟antileech，然后复制libantiLeech.so到~/.aMule,使用amuled.
配置参数为：
          --prefix=/usr \
          --mandir=/usr/share/man \
          --enable-debug \
          --enable-amule-daemon \
          --enable-amulecmd \
          --enable-amule-gui \
          --enable-webserver \
          --enable-cas \
          --enable-wxcas \
          --enable-alc \
          --enable-alcc \
          --enable-geoip \
          --enable-upnp \
          --with-denoise-level=3 \
          --enable-nls \
          --enable-optimize \
          --enable-mmap \
          --enable-ccache \
          --with-wxversion=3.0
不断刷log

> Logger.cpp(326): Error: Failed to add descriptor 9 to epoll descriptor 6 (error 17: File exists)

**Comment by persmule** [comment]
问题肯定不在 Logger.cpp(326)，能否抓个 backtrace 出来？

**Comment by xf1** [comment]
程序不崩溃应该怎么调试？用amulecmd关闭，backtrace 没有输出。
![log](https://cloud.githubusercontent.com/assets/6897578/24787900/4cde0b5a-1b9d-11e7-8f82-1bb32b53e23e.png)

**Comment by persmule** [comment]
一开始就用 gdb 启动程序，然后在 Logger.cpp(326) 下断点呗。看到输出类似的错误就 backtrace。

**Comment by xf1** [comment]
gdb跟amule的日志：
[amuled.txt](https://github.com/persmule/amule-dlp/files/907101/amuled.txt)
[gdb.txt](https://github.com/persmule/amule-dlp/files/907100/gdb.txt)
debug模式编译的只会单线程0-30%，关了debug才会100%.
还有编译antileech时，那个头文件不知道有关系不？
> checking for wx-config... wx-config
> checking for string.h... (cached) yes
> ./configure: line 15915: wx/string.h: No such file or directory

**Comment by persmule** [comment]
试过上游版本 https://github.com/amule-project/amule 吗？有无同样的问题？
头文件没有关系。

**Comment by persmule** [comment]
对了，https://github.com/persmule/amule-dlp/wiki/Installation 早已更新，configure 的时候请注意加上 --with-boost。

**Comment by xf1** [comment]
非常感谢，确实是这个问题。
另外自带的 debian/rules 默认也没使用 boost，以前用来打包也出现过问题。

**Comment by persmule** [comment]
自带的 debian/rules 早就老得牙都掉了，连 debian 自己都不参考。
