### ISSUE TITLE
运行一阵后两个在不同机器上的aMule-DLP的UserHash变为相同

### ISSUE THREAD

**Issue by maidmeow4** [persmule/amule-dlp#28]
A机在Google Cloud上，B机在局域网内，都是Github clone下来的源码编译成。
运行一段时间后，发现两个UserHash都变为`1054A144090EA2CA4CBF65F6DD756F9E`
`md5sum`校验配置目录下的`preferences.dat`，结果都为`e6bb7ec8deb6451feb517d26c7b7bacf`

删除`preferences.dat`和`cryptkey.dat`后确实生成了新的UserHash，但一段时间后仍然会变成上面的值。
![2017-06-01_091825](https://cloud.githubusercontent.com/assets/8447650/26660560/6c04a2ee-46ab-11e7-9460-582d3cc88d9d.png)
![2017-06-01_091840](https://cloud.githubusercontent.com/assets/8447650/26660561/6c06b278-46ab-11e7-86a4-0f486179c047.png)

**Comment by persmule** [comment]
调查过 cryptkey.dat 改变时 amule 的日志吗？

还有，preferencesKad.dat 是否和其他两个文件一起删除了？

**Comment by maidmeow4** [comment]
没有调查过日志。（我也不清楚UserHash改变是什么时候发生的）

之前删除时共删除了`preferences.dat`、`preferenceKad.dat`、`clients.met`和`cryptkey.dat`。

另外我发现尽管`preferences.dat`的MD5是相同的，但`cryptkey.dat`的MD5不同。

**Comment by persmule** [comment]
那么请调查日志，看看到底发生了什么。

**Comment by maidmeow4** [comment]
Hashes didn't change since last reset, I'll re-open this issue if any thing happens.
