### ISSUE TITLE
Api mismatch with crypto++ 6.0.0

### ISSUE THREAD

**Issue by TommyJerryMairo** [persmule/amule-dlp#29]
```
Compiling ClientCreditsList.cpp
ClientCreditsList.cpp: In member function ‘void CClientCreditsList::InitalizeCrypting()’:
ClientCreditsList.cpp:315:10: error: ‘CryptoPP::RSASSA_PKCS1v15_SHA_Verifier {aka class CryptoPP::PK_FinalTemplate<CryptoPP::TF_VerifierImpl<CryptoPP::TF_SignatureSchemeOptions<CryptoPP::TF_SS<CryptoPP::RSA, CryptoPP::PKCS1v15, CryptoPP::SHA1, int>, CryptoPP::RSA, CryptoPP::PKCS1v15_SignatureMessageEncodingMethod, CryptoPP::SHA1> > >}’ has no member named ‘DEREncode’
   pubkey.DEREncode(asink);
          ^~~~~~~~~
make[3]: *** [Makefile:1897: amule-ClientCreditsList.o] Error 1
make[2]: *** [Makefile:3408: all-recursive] Error 1
make[1]: *** [Makefile:584: all-recursive] Error 1
make: *** [Makefile:491: all] Error 2
```

Get this error while compiling with newly upgraded `libcrypto++` version `6.0.0`

As the new version has fixed a few published vulnerability issues, I believe it's a good decision if `amule-dlp` can adapt to the new version library.

**Comment by persmule** [comment]
This project of mine does not aim at adaptation, which is the responsibility of [upstream](https://github.com/amule-project/amule/), to whom your wish had better be reported.
Besides, [This issue](https://github.com/amule-project/amule/issues/119) seems related to yours.

**Comment by TommyJerryMairo** [comment]
[Upstream](https://github.com/amule-project/amule/commit/27c13f3e622b8a3eaaa05bb62b0149604bdcc9e8) has been updated. Please fetch it as soon as possible.

**Comment by persmule** [comment]
I have already rebase my master branch upon it.
