### ISSUE TITLE
Fix for Issue #29 is NOT Merged

### ISSUE THREAD

**Issue by biergaizi** [persmule/amule-dlp#32]
The latest master branch fails to compile Fedora 29 with Crypto++ 7.0, raising the following error message

```
ClientCreditsList.cpp:315:10: error: ‘CryptoPP::RSASSA_PKCS1v15_SHA_Verifier {aka class CryptoPP::PK_FinalTemplate<CryptoPP::TF_VerifierImpl<CryptoPP::TF_SignatureSchemeOptions<CryptoPP::TF_SS<CryptoPP::RSA, CryptoPP::PKCS1v15, CryptoPP::SHA1, int>, CryptoPP::RSA, CryptoPP::PKCS1v15_SignatureMessageEncodingMethod, CryptoPP::SHA1> > >}’ has no member named ‘DEREncode’
   pubkey.DEREncode(asink);
```

This issue has already reported by @TommyJerryMairo, and fixed in the upstream repo as https://github.com/amule-project/amule/commit/27c13f3e622b8a3eaaa05bb62b0149604bdcc9e8. <del>However, the old code is still in the aMule-DLP repo</del>.

**Comment by persmule** [comment]
Rebased master has been pushed.
