### ISSUE TITLE
compilation on macOS Mojave 10.14

### ISSUE THREAD

**Issue by pthall** [persmule/amule-dlp#36]
have compilation errors on macOS Mojave 10.14 that I haven't been able to resolve.

wxWidgets 3.0.4 was compiled:

```
$ ls -l /usr/local/bin/wx*
lrwxr-xr-x  1 root        wheel            53 May 26 10:37 /usr/local/bin/wx-config -> /usr/local/lib/wx/config/osx_cocoa-unicode-static-3.0
lrwxr-xr-x  1 root        wheel             8 May 26 10:37 /usr/local/bin/wxrc -> wxrc-3.0
-rwxr-xr-x@ 1 localuser  1073494981  1360400 May 26 10:34 /usr/local/bin/wxrc-3.0
```

The error which seems relevant from error_output. I double-checked that I have bison and flex installed (from MacPorts):

```
./Parser.y:4:10: fatal error: 'Scanner.h' file not found
#include "Scanner.h"
         ^~~~~~~~~~~
1 error generated.
make[3]: *** [libmuleappcore_a-Parser.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

```
$ find . -name "Scanner*"
./src/Scanner.l
./src/Scanner.cpp
./src/Scanner.h.in
```

Configure parameters for wxWidgets:

`./configure --disable-shared --enable-unicode --disable-debug --disable-debug_gdb --with-macosx-version-min=1`

Configure parameters for aMule:
```
    ./configure --enable-optimize --with-crypto-prefix=/opt/local --with-gdlib-prefix=/opt/local \
    --enable-cas --enable-webserver \
    --enable-amulecmd --enable-amule-gui --enable-wxcas --enable-alc --enable-alcc --enable-amule-daemon --enable-geoip \
    --with-geoip-lib=/opt/local/lib --with-geoip-headers=/opt/local/include --with-libpng-prefix=/opt/local --disable-debug
```

config.log:
https://pastebin.com/Fg4iY5v9

configure:
https://gist.github.com/pthall/c4ad8d6868a208b0decf762e223aa69b

Thanks for any help in advance.

**Comment by persmule** [comment]
You should delete ./src/Scanner.cpp and try again, since Scanner.h should be generated along with Scanner.cpp, but a make rule could only have one single target. (see [this](https://github.com/amule-project/amule/issues/12))

**Comment by pthall** [comment]
Thanks for the bug reference and tip. I deleted Scanner.cpp, and make produced the same error.

**Comment by pthall** [comment]
I resolved by manually generating the file with flex before running configure and make
`flex --header-file=./Scanner.h -o Scanner.cpp ./Scanner.l`
Now working through some issues with libiconv
