### ISSUE TITLE
请问：如何怎么编译 Windows 版？？？

### ISSUE THREAD

**Issue by SAYoung00** [persmule/amule-dlp#37]
我用visual studio编译，只能编译出官方以前发布的2.3.1那个样子：dlp功能没编译出来；并无中文，根本看不懂啊！！！

**Comment by persmule** [comment]
作者手中没有任何 Windows 环境，且没有支持包括 Windows 在内的非 *nix 系统的任何打算，如果你一定要在 Windows 下使用，建议在 cygwin 下以和其他 *nix 系统相同的方式编译（即安装好依赖的包，如 libwx_gtk3u3.0-devel 等后 configure、make，多年以前亲测有效）。
当然，[放弃萎软的恶意系统](https://getgnulinux.org/zh)对你更有好处，相信我，真的。

**Comment by minnyres** [comment]
尝试编译了一个Windows版，需要的话可以从这里下载：

https://github.com/minnyres/amule-win32/releases

最简单的方法还是在Linux系统通过MinGW-w64的交叉编译工具链编译Windows版本。需要对代码打一点补丁避免编译报错。还有编译libantileech的时候用libtool生成Windows的动态库有些问题，我只能直接用GCC生成动态库

    $TARGET-g++ -O2 -s -fPIC -shared antiLeech.cpp antiLeech_wx.cpp Interface.cpp -o antileech.dll $(wx-config --cppflags) $(wx-config --libs)

可以参考我的编译脚本和补丁：https://github.com/minnyres/amule-win32
