### ISSUE TITLE
挺ls

### ISSUE THREAD

**Issue by ghost** [persmule/amule-dlp#4]
clone 下来的和下载压缩包的有区别吗？clone的实在太慢。我的错误和楼上的一样，不知道怎么解决了。

现在网上完全没有其他的资料，希望大大快点给出解决方案。

还有，你建立的软件库一团糟，根本不能用

make[3]: **\* No rule to make target 'Scanner.h', needed by 'all-am'。 停止。
make[3]: **\* 正在等待未完成的任务....
Makefile:3420: recipe for target 'all-recursive' failed
make[2]: **\* [all-recursive] Error 1
Makefile:573: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
Makefile:477: recipe for target 'all' failed
make: **\* [all] Error 2

clone下来又试了试，还是这样
手残在出现这个终止之后又输入了一次make，好像通过了，之后make install，能打开了。

**Comment by persmule** [comment]
已修复，请merge最新的master分支。

问题在于Scanner.h是在生成Scanner.cpp的过程中生成的，但Makefile中缺乏显式生成Scanner.h的规则，但存在显式生成Scanner.cpp的规则。导致若一条需要Scanner.h的规则在生成Scanner.cpp前执行则必然失败，但一旦生成了Scanner.cpp，Scanner.h就会存在，再次make也就会通过。

解决的方法是在Makefile中添加一条规则，使Scanner.h依赖Scanner.cpp（无需命令）即可。如此当需要Scanner.h但该文件不存在时make即可自动调用生成Scanner.cpp的规则来同时生成Scanner.cpp和Scanner.h。

详情请通过diff对比。
