### ISSUE TITLE
No amule.xpm

### ISSUE THREAD

**Issue by TommyJerryMairo** [persmule/amule-dlp#6]
I use command :

```
./autogen.sh
./configure --prefix=/usr
make
```

But it seems that no amule.xpm in the source file

```
make[2]: *** No rule to make target 'amule.xpm', needed by 'all-am'.  Stop.
```

But, in [other's repo](https://github.com/windreamer/amule-dlp) there are amule.xpm indeed.

So, is it a mistake or a something truly different?

**Comment by biergaizi** [comment]
```
cd src/pixmaps/flags_xpm
./makeflags.sh
```

You shall generate the XPMs first.

**Comment by biergaizi** [comment]
@persmule We probably need to put this into `README`.

**Comment by Artoria2e5** [comment]
Shouldn't that be part of makefile resolution though?

**Comment by TommyJerryMairo** [comment]
@biergaizi That's no use, still the same error.

**Comment by TommyJerryMairo** [comment]
After

```
cd src/pixmaps/flags_xpm
./makeflags.sh
cd $OLDPWD
```

Then I run `find . -name amule.xpm`

Still nothing found.

**Comment by Artoria2e5** [comment]
src/aMule.xpm, debian/amule-32.xpm.

(Don't use the debian dir as a packaging reference -- it appears to be written for aMule.)

**Comment by TommyJerryMairo** [comment]
@Arthur2e5 I use `cp src/pixmaps/flags_xpm/cn.xpm ./amule.xpm` and it words.

Before `make` there is no such file `src/amule.xpm`
